// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "WIFI SSID"
#define SECRET_PASS "PASSWORD"

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a9ynq6vqcv80-ats.iot.us-east-1.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICiTCCAXGgAwIBAgIVALno5ZpyKP9Q2uL4CsgU/iddAsFTMA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMDExMjIwNDUx
NThaFw00OTEyMzEyMzU5NTlaMBgxFjAUBgNVBAMTDU15TUtSV2lGaTEwMTAwWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAATuyHk0PG+svxTqnjoNf6/HBwGbGF6fjS+4
jkK7imu0Q311BIqpzzyxY/01Unp3a0YPdiqed2qzqLWqGBrkwVmPo2AwXjAfBgNV
HSMEGDAWgBRn2EFONHorXoIR/jtZPw4Cdjf3VjAdBgNVHQ4EFgQUCQlA86lMJuYj
O//5a40eXtAfaF8wDAYDVR0TAQH/BAIwADAOBgNVHQ8BAf8EBAMCB4AwDQYJKoZI
hvcNAQELBQADggEBAFO85Za0TJbcLwbMZObrKD/LRk2RlkQuzfgYxFXvfg1O7KWn
1zSDaN4tKXT9a6M0EgP4PuoCYDfeHb4Ro223Pc7Wb+1sCr0NSAu87DS42C7Smuqm
QkhjrjXt+Acu5M8sTKspdmGGB3aHsNzEAiHkM/J3KeiTcxTGLjV9qQzLRceVzkcT
JNTQ33Ty55k/1HxHIcLyF82TQCmuEbc1yp7lvtWBvuazOgdPZMNGQ2N8k5uFPaBb
Xl0W9HrSZJpoMwAbLOqShTBQRpJTHrGznUJgKl/f5sddaN01lB5BN/wU6b6BBe7A
zT5L+98rlpxR8YKQlatYKe9xZXGKR3M5ht8PuSw=
-----END CERTIFICATE-----
)";
